### ISSUE TITLE
Bartender is down, now what?

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/bartender#1]
This issue is to address what BEERGARDEN should do when bartender goes down/ There are a lot of options for how to handle this. I suspect issues will be spawned in reference to this issue, but I wanted to keep this here for historic purposes.

When bartender goes down, requst processing fundamentally stops.

* How should beer-garden report this status?
* How can beer-garden recover automatically?
* What should the plugins do
  * Remote Plugins?
  * Local Plugins?

**Comment by hazmat345** [comment]
This will not be addressed in 2.4.0 and it will be made OBE by beer-garden/beer-garden#87. If plans change this can be reopened, but I'm closing this since as of now we won't be fixing.
